name: GitHub Actions Demo

on:
  push:
    branches: [main]
    paths-ignore: [ .github/ ]
  schedule: [cron: '15 6 * * 0']
  workflow_dispatch:

jobs:
  Build:
    runs-on: docker://ubuntu-latest
    steps:
      - run: |
          echo "Triggered from ${{ github.event_name }}"
          echo "For reference ${{ github.ref }}"
      - name: list files
        run: tree
      
